import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import gsap from 'gsap'
import {ScrollTrigger} from 'gsap/dist/ScrollTrigger'
import { useEffect,useRef, useState } from 'react'
import { motion,useScroll } from "framer-motion"
gsap.registerPlugin(ScrollTrigger)

export default function Home() {

  const {scrollY} = useScroll()
  const [isFixed,setIsFixed] = useState(true)
  const [y,setY] = useState(0)
  const [opacity,setOpacity] = useState(0)
  const [menuOpacity,setMenuOpacity] = useState(0)
  useEffect(() => {
    scrollY.onChange((y) => {
      setIsFixed(y < window.innerHeight-320)
      setY(y)
      setOpacity((y/(window.innerHeight/3)))
      setMenuOpacity((y/(window.innerHeight)))
      console.log(y);
    })
    console.log("herhangi bir şey");
  }, [])
  console.log(isFixed);
  const topBean = useRef(null)
  const bottomBean = useRef(null)
  
  return (
    <>
      <Head>
        <title>Selen&apos;s Homemade Coffee Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.landing}>
        <motion.div className={styles.topBeans} style={{position: isFixed ? 'fixed' : 'absolute',bottom: !isFixed && '160px'}}/>     
        <h1 className={styles.title} style={{opacity:1-opacity,position:'absolute',top:'50%',transform:`translateY(${-y/5}px)`}}>
            Selen&apos;s Homemade Coffee Shop
        </h1>
        <div className={styles.botBeans} ref={bottomBean}/>
      </div>

      <div className={styles.container} style={{opacity:menuOpacity}}>
        <main className={styles.main}>

          <h2 className={styles.menu}>
            Menu
          </h2> 
          <div className={styles.card}>
            <h3 className={styles.subtitle}>
              Sıcak Kahveler
            </h3>
            <p className={styles.coffee}>Espresso</p>
            <p className={styles.coffee}>Americano</p>
            <p className={styles.coffee}>Filtre Kahve Çeşitleri</p>
            <p className={styles.coffee}>Latte</p>
            <p className={styles.coffee}>Cappucino</p>
            <p className={styles.coffee}>Türk Kahvesi</p>
          </div>
          <div className={styles.card}>
            <h3 className={styles.subtitle}>
              Soğuk Kahveler
            </h3>
            <p className={styles.coffee}>Iced Americano</p>
            <p className={styles.coffee}>Iced Latte</p>
            <p className={styles.coffee}>Cold Brew</p>
          </div>
          <div className={styles.card}>
            <h3 className={styles.subtitle}>
              Çaylar
            </h3>
            <p className={styles.coffee}>lorem ipsum</p>
          </div>
          <div className={styles.card}>
            <h3 className={styles.subtitle}>
              Aromalar
            </h3>
            <p className={styles.coffee}>Karamel</p>
            <p className={styles.coffee}>Vanilya</p>
            <p className={styles.coffee}>Beyaz Çikolata</p>
            <p className={styles.coffee}>Çikolata</p>
          </div>
          <div className={styles.card}>
            <h3 className={styles.subtitle}>
              Kahve Çekirdekleri
            </h3>
            <p className={styles.coffee}>Starbucks Guatemala</p>
            <p className={styles.coffee}>Starbucks Odyssey</p>
            <p className={styles.coffee}>Costa Dark Roast</p>
            <p className={styles.coffee}>Jacobs Monarch</p>
            <p className={styles.coffee}>Mümin&apos;s Special</p>
          </div>
        </main> 
      </div>
    </>
  )
}
